apiVersion: v1
kind: ConfigMap
metadata:
  name: elastic-search-config
data:
  ELASTIC_SEARCH_HOST_PORT: http://host.minikube.internal:9200
  ELASTIC_SEARCH_USERNAME: elastic
  ELASTIC_SEARCH_PASSWORD: elastic   # should become Secret later
