apiVersion: v1
kind: ConfigMap
metadata:
  name: kafka-config
data:
  KAFKA_HOST_PORT: host.minikube.internal:9092
  KAFKA_NEW_POST_FANOUT_TOPIC: post-fanout
  KAFKA_NEW_POST_TOPIC: new-post
  KAFKA_I_FOLLOWED_FANOUT_TOPIC: i-followed
  KAFKA_I_UNFOLLOWED_FANOUT_TOPIC: i-unfollowed
  KAFKA_NEW_POST_LIKE_TOPIC: post-like
