apiVersion: v1
kind: ConfigMap
metadata:
  name: service-url-config
data:
  USER_SERVICE_USERID_URL: http://host.minikube.internal:80/v1/user/userid/
  USER_SERVICE_SIGN_IN_URL: http://host.minikube.internal:80/v1/user/signin/
  WHO_FOLLOWS_ME_URL: http://host.minikube.internal:80/v1/follower/who-follows-me/
  I_FOLLOW_URL: http://host.minikube.internal:80/v1/follower/i-follow/
  GET_POST_BY_USER_URL: http://host.minikube.internal:80/v1/post/get-by-user/
  GET_POST_BY_POST_ID_URL: http://host.minikube.internal:80/v1/post/get/
  AUTH_REFRESH_URL: http://host.minikube.internal:80/v1/auth/refresh/
  AUTH_VERIFY_URL: http://host.minikube.internal:80/v1/auth/verify/
  AUTH_AUTHORIZE_URL: http://host.minikube.internal:80/v1/auth/authorize/
  AUTH_SIGN_IN_URL: http://host.minikube.internal:80/v1/auth/signin/
  AUTH_SIGN_OUT_URL: http://host.minikube.internal:80/v1/auth/signout/
