apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
  name: analytics
subjects:
  - kind: ServiceAccount
    name: analytics
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: Role
  name: analytics
