apiVersion: v1
kind: Service
metadata:
  name: file-service
spec:
  selector:
    app: file-service
  ports:
    - protocol: TCP
      port: 3008
      targetPort: 5008
      nodePort: 30008
  type: NodePort