apiVersion: v1
kind: ConfigMap
metadata:
  name: user-service-config
data:
  SERVICE_NAME: user-service
  SERVICE_VERSION: 1.0.0
  REDIS_USERNAME_TTL_SEC: "86400" # 1day
  API_PATH_ROOT: /v1/user
  JWT_ACCESS_SECRET: really_hard_access_token
  JWT_REFRESH_SECRET: really_hard_refresh_token
  JWT_ACCESS_EXPIRES: 15m
  JWT_REFRESH_EXPIRES: 7d
