apiVersion: v1
kind: Service
metadata:
  name: timeline-service
spec:
  selector:
    app: timeline-service
  ports:
    - protocol: TCP
      port: 3001
      targetPort: 5001
      nodePort: 30001
  type: NodePort