apiVersion: v1
kind: ConfigMap
metadata:
  name: fanout-service-config
data:
  SERVICE_NAME: fanout-service
  SERVICE_VERSION: 1.0.0
  API_PATH_ROOT: /v1/fanout
  KAFKA_CLIENT_ID: fanout
  KAFKA_FANOUT_GROUP: fanout-group
  KAFKA_MAX_POST_SET_SIZE: "100"
  TOPK_UPDATER_ENABLED: "false"
  TOPK_TICK_INTERVAL_MS: "2000"
  TOPK_BATCH_SIZE: "2000"
  TOPK_HEAD_REFRESH_INTERVAL_MS: "60000"
  TOPK_HEAD_REFRESH_SIZE: "1000"
  TOPK_MAX_SIZE: "5000"
  TOPK_WINDOW_SECONDS: "3600"
  TOPK_BUCKET_SIZE_SECONDS: "60"
  TOPK_METRIC: "likes"
  TOPK_SEGMENT: "global"
  TOPK_BUCKET_SUFFIX: "m"
  TOPK_CHANGED_SET_KEY: "chg:likes:global:1h"
  TOPK_KEY: "topk:likes:global:1h"
