apiVersion: v1
kind: ConfigMap
metadata:
  name: fanout-service-config
data:
  SERVICE_NAME: fanout-service
  SERVICE_VERSION: 1.0.0
  API_PATH_ROOT: /v1/fanout
  KAFKA_CLIENT_ID: fanout
  KAFKA_FANOUT_GROUP: fanout-group
  KAFKA_MAX_POST_SET_SIZE: "100"
