apiVersion: v1
kind: ConfigMap
metadata:
  name: fanout-service-config
data:
  SERVICE_NAME: fanout-service
  SERVICE_VERSION: 1.0.0
  API_PATH_ROOT: /v1/fanout
  KAFKA_CLIENT_ID: fanout
  KAFKA_FANOUT_GROUP: fanout-group
  KAFKA_MAX_POST_SET_SIZE: "100"
  TOPK_1H_ENABLED: "false"
  TOPK_1H_TICK_INTERVAL_MS: "2000"
  TOPK_1H_BATCH_SIZE: "2000"
  TOPK_1H_HEAD_REFRESH_INTERVAL_MS: "60000"
  TOPK_1H_HEAD_REFRESH_SIZE: "1000"
  TOPK_1H_MAX_SIZE: "5000"
  TOPK_1H_WINDOW_SECONDS: "3600"
  TOPK_1H_BUCKET_SIZE_SECONDS: "60"
  TOPK_1H_METRIC: "likes"
  TOPK_1H_SEGMENT: "global"
  TOPK_1H_BUCKET_SUFFIX: "m"
  TOPK_1H_CHANGED_SET_KEY: "chg:likes:global:1h"
  TOPK_1H_KEY: "topk:likes:global:1h"
  TOPK_24H_ENABLED: "false"
  TOPK_24H_TICK_INTERVAL_MS: "30000"
  TOPK_24H_BATCH_SIZE: "2000"
  TOPK_24H_HEAD_REFRESH_INTERVAL_MS: "300000"
  TOPK_24H_HEAD_REFRESH_SIZE: "1000"
  TOPK_24H_MAX_SIZE: "5000"
  TOPK_24H_WINDOW_SECONDS: "86400"
  TOPK_24H_BUCKET_SIZE_SECONDS: "3600"
  TOPK_24H_METRIC: "likes"
  TOPK_24H_SEGMENT: "global"
  TOPK_24H_BUCKET_SUFFIX: "h"
  TOPK_24H_CHANGED_SET_KEY: "chg:likes:global:24h"
  TOPK_24H_KEY: "topk:likes:global:24h"
  TOPK_30D_ENABLED: "false"
  TOPK_30D_TICK_INTERVAL_MS: "300000"
  TOPK_30D_BATCH_SIZE: "2000"
  TOPK_30D_HEAD_REFRESH_INTERVAL_MS: "900000"
  TOPK_30D_HEAD_REFRESH_SIZE: "1000"
  TOPK_30D_MAX_SIZE: "5000"
  TOPK_30D_WINDOW_SECONDS: "2592000"
  TOPK_30D_BUCKET_SIZE_SECONDS: "86400"
  TOPK_30D_METRIC: "likes"
  TOPK_30D_SEGMENT: "global"
  TOPK_30D_BUCKET_SUFFIX: "d"
  TOPK_30D_CHANGED_SET_KEY: "chg:likes:global:30d"
  TOPK_30D_KEY: "topk:likes:global:30d"
