apiVersion: apps/v1
kind: Deployment
metadata:
  name: fanout-service
spec:
  replicas: 3
  selector:
    matchLabels:
      app: fanout-service
  template:
    metadata:
      labels:
        app: fanout-service
    spec:
      containers:
        - name: fanout-service-container
          image: tareqjoy/fanout-service:latest
          imagePullPolicy: Always
          ports:
            - containerPort: 5004
          livenessProbe:
            httpGet:
              path: /health
              port: 5004
            initialDelaySeconds: 10
            periodSeconds: 10
            timeoutSeconds: 2
            failureThreshold: 3
          readinessProbe:
            httpGet:
              path: /ready
              port: 5004
            initialDelaySeconds: 5
            periodSeconds: 10
            timeoutSeconds: 2
            failureThreshold: 3
          envFrom:
            - configMapRef:
                name: fanout-service-config
            - configMapRef:
                name: kafka-config
            - configMapRef:
                name: service-url-config
            - configMapRef:
                name: redis-config
            - configMapRef:
                name: mongodb-config
