apiVersion: v1
kind: Service
metadata:
  name: fanout-service
spec:
  selector:
    app: fanout-service
  ports:
    - protocol: TCP
      port: 3004
      targetPort: 5004
      nodePort: 30004
  type: NodePort