apiVersion: apps/v1
kind: Deployment
metadata:
  name: follower-service
spec:
  replicas: 3
  selector:
    matchLabels:
      app: follower-service
  template:
    metadata:
      labels:
        app: follower-service
    spec:
      containers:
        - name: follower-service-container
          image: tareqjoy/follower-service:latest
          imagePullPolicy: Always
          ports:
            - containerPort: 3000
          envFrom:
            - configMapRef:
                name: follower-service-config
            - configMapRef:
                name: neo4j-config
            - configMapRef:
                name: service-url-config
            - configMapRef:
                name: kafka-config