apiVersion: v1
kind: Service
metadata:
  name: follower-service
spec:
  selector:
    app: follower-service
  ports:
    - protocol: TCP
      port: 3003
      targetPort: 5003
      nodePort: 30003
  type: NodePort