apiVersion: v1
kind: ConfigMap
metadata:
  name: auth-service-config
data:
  SERVICE_NAME: auth-service
  SERVICE_VERSION: 1.0.0
  API_PATH_ROOT: /v1/auth
  JWT_ACCESS_SECRET: test_access_secret_key_00x
  JWT_REFRESH_SECRET: test_refresh_secret_key_00x
  JWT_ACCESS_EXPIRES_SEC: "30"
  JWT_REFRESH_EXPIRES_SEC: "1296000"
  AUTH_CODE_EXPIRES_SEC: "120"
